# Generated by Django 6.1 on 2026-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=100)),
                ('bride_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=1000)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('template', models.CharField(default='wedding-1', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
